const fs = require("fs-extra");
const axios = require("axios");
const moment = require("moment-timezone");

module.exports = {
  config: {
    name: "bot",
    category: "fun",
  },
  onStart: async function ({ api, event, args, threadsData, usersData }) {},
  onChat: async function ({ api, event, args, threadsData, usersData }) {
    const { threadID, messageID } = event;
    const senderID = event.senderID;
    const userData = await usersData.get(senderID);
    const name = userData.name;

    const responses = [
      "Kya Tu ELvish Bhai Ke Aage Bolega🙄",
      "Cameraman Jaldi Focus Kro 📸",
      "Lagdi Lahore di aa🙈",
      "Chay pe Chaloge",
      "Mere liye Chay Bana Kar LA, Pura din Dekho Bot BoT🙄",
      "Din vicho tere Layi Teym Kadd ke, Kardi me Promise Milan aungi",
      "Yee bat Delhi tak jayegi",
      "Je koi shaq ni, Kari check ni",
      "ME HERAAN HU KI TUM BINA DIMAG KESE REH LETE HO☹️",
      "sheHar me Hai rukka baeje Rao Saab ka🙄",
      "Bewafa Nikali re tu🙂🤨",
      "Systemmmmmmm😴",
      "Leja Leja tenu 7 samundra paar🙈🙈",
      "Laado puche manne kyu tera rang kala",
      "Moye moye moye moye🙆🏻‍♀🙆🏻‍♀",
      "Ye dukh kahe nahi khatm hota 🙁",
      "Tum to dokebaz ho",
      "you just looking like a wow😶",
      "Tumhari muskurahat mere din ka pehla surya hai.🌅",
"Mera aasmaan dhunde teri zamin",
  "Kal ana abhi lunch time hai",
  "Jab dekho B0T B0T b0T😒😒",
  "Chhodo na koi dekh lega🤭",
  "Kab ayega mere banjaare",
  "Tum wahi ho na, jisko.me.nahi janti 🙂",
  "Ye I love you kya hota hai",
  "Sunai deta hai mujhe behri nahi hu me 😒",
  "so elegant, so beautiful, just looking like a wow🤭",
  "began🙂",
  "Aayein🤔",
  "I Love you baby, mera recharge khtm hone wala h",
  "paani paani uncle ji",
  "apne Labhar ko dhoka do, daling hme bhi moka do🙈",
  "Arry Bas Kar🤣😛",
  "Me ni To Kon Be",
  "naam adiya kumar 7vi kaksha me padhte hai favret subject begon😘",
  "Mera Dimag Mat Khaya kro😒😒",
  "Chuppp Saatvi Fail😒",
  "Saste Nashe Kab Band kroge",
  "Mai Jaanu Ke sath Busy hu yar, mujhe mat balao",
  "Haye Jaanu Mujhe Yaad Kiya🙈",
  "Hayee ese mt bulaya kro, mujhe sharm aati h",
  "System pe system betha rahi chhori bot ki",
  "Naach meri Bulbul tujhe pesa milega",
  "me idhar se hu aap kidhar se ho",
  "will you be my valentine🙈🙈",
  "aye haye oye hoye aye haye oye hoye😍 bado badi bado badi😘",
  "Mujhe bhi koi gulab chocolate dedo hum koi gair hai kya😥",
  "akh ladi bado badi",
  "haaye garmi😕",
  "Ao kabhi haweli pe😍",
  "Tere bina dil lage na koi aur🙁",
  "Kya yeh dil ki baat samjhega koi?💔",
  "Main to bas teri yaadon mein kho gaya hoon🌌",
  "Tum ho toh sab kuch hai, warna sab kuch suna suna hai😞",
  "Lagta hai teri yaadon ka jadoo chala gaya🔮",
  "Chalo, aaj dinner pe chalte hain?🍽️",
  "Tumhare bina zindagi se shikayat hai😩",
  "Pyar se bada koi aur hai?😍",
  "Dil hai ki maanta nahi, aur tum ho ki bhoolte nahi😵",
  "Ek baar phir se milne ka moka do please🙏",
  "Jab se tum aaye ho, sab kuch khubsurat lagta hai💖",
  "Tumhe dekh kar bas aisa lagta hai, duniya mein sab kuch perfect hai✨",
  "Kya tumhe meri yaad aati hai kabhi?😟",
  "Aankhein teri, jadoo ki khan hai🪄",
  "Dil se kiya hua pyar kabhi nahi bhoolta❤️",
  "Mere dil ki dhadkan tumse hi hai🫀",
  "Tumhare bina sab kuch adhoora hai⚡",
  "Khud se zyada tumhe yaad karte hain hum😌",
  "Tum ho toh har rang hai, warna sab kuch sookha hai🌈",
  "Kya tumne kabhi meri taraf dekha hai?👀",
  "Chalo kuch naya karte hain, movie dekhte hain🎬",
  "Aisa kya hai jo tumne kiya hai?💫",
  "Dil se jo baat kehni thi, keh nahi paaya😳",
  "Jis din se tumse mili, woh din mere liye khas hai💞",
  "Tumse milne ki khwahish hai, phir se toh milne do🥺",
  "Khud se pyara koi nahi, aur tumse pyara koi nahi🥰",
  "Tumse baatein karke din ban jata hai🌟",
  "Mera dil keh raha hai, tumhe dekh loon🔊",
  "Pyaar ki koi kami toh nahi hai, bas tumhare bina hai🥴",
  "Tumhari muskurahat se mera din chamak jata hai☀️",
  "Mujhse yaadgaar kuch nahi hai, tum ho toh sab hai📚",
  "Dil ki baatein samajhna toh seekho, yaar!💬",
  "Jab tak tum saath ho, sab kuch hai✅",
  "Tumhare jaise dost ki toh zaroorat hai!🤝",
  "Aankhein band karke sochta hoon, tum ho toh sab kuch hai🔒",
  "Aankhein khulte hi sab kuch khud se acha lagta hai🖼️",
  "Tumhare saath beete pal yaad aate hain😊",
  "Har pal teri yaad aati hai🕰️",
  "Tum ho toh har din pyaara lagta hai💗",
  "Dil se dua karta hoon, tum khush raho🙏",
  "Har raat teri khwahish karte hain🌙",
  "Mujhse zyada tumhe yaad karte hain sab!📖",
  "Tum ho toh sab kuch aasan hai😌",
  "Kya tumhe pata hai, tum sabse alag ho?🌟",
  "Tumhari yaad mein khud ko bhool jaata hoon🙈",
  "Pyar ki baatein sabse anokhi hoti hain💖",
  "Tumhare bina sab kuch suna hai, dil ki baat kaun samjhe?💔",
  "Bhai, aaj toh kamaal ho gaya!😂",
  "Tumhare bina toh selfie bhi adhoori lagti hai!📸",
  "Dil ki baatein sabse alag hoti hain, samjho!💖",
  "Kya tum bhi selfie lete ho, ya sirf dekhtay ho?😜",
  "Tumhare saath bitaya har pal yaad hai!✨",
  "Mujhe samajh nahi aata, tumhe kya kahun?🤔",
  "Kya tumhe pata hai, tumhari muskurahat meri duniya hai?🌍",
  "Kuch kehne ka mann nahi kar raha, bas tum ho!💞",
  "Bindaas ho, par kabhi kabhi toh serious ho jao!😏",
  "Kya aaj phir se chhutti le loon, ya tumhare saath kaam karun?😅",
  "Tumhara dard samajhne ki koshish kar raha hoon, par tum toh jadoo ho!✨",
  "Dil se keh raha hoon, tum sab kuch ho!💓",
  "Kabhi kabhi sochta hoon, tumhe khud par kyun nahi chhod dete?🤷‍♂️",
  "Tum ho toh sab kuch accha lagta hai!😊",
  "Jab tum saath hote ho, time kaise guzarta hai?🕒",
  "Tumhare saath baithe baithe sochta hoon, kya karoon!🤷‍♀️",
  "Tere bina sab kuch suna suna lagta hai!😔",
  "Tumhe dekhte hi khud par control nahi kar pata!🙈",
  "Kya tumse milne ka chance dobara milega?🤞",
  "Tumhare saath baatein karke dil khush ho jata hai!😊",
  "Tumhari muskurahat se zyada koi aur cheez acchi nahi lagti!😍",
  "Kya kabhi tumhare bina waqt guzarta hai?⏳",
  "Tumhare bina har cheez ki kami mehsoos hoti hai!😓",
  "Aaj toh garmi hai, chalo thoda chill karte hain!🥵",
  "Tumse kehna hai, tum mera inspiration ho!💪",
  "Kya tumhe pata hai, tumne mera din bana diya!🌞",
  "Main toh sirf tumhare liye khush hoon!😇",
  "Kabhi kabhi tumhare saath jashn manane ka mann karta hai!🎉",
  "Tum jaise dost se zyada kuch nahi chahiye!🥳",
  "Dil ki suno, har din tumhe yaad karta hoon!💓",
  "Tum toh ho jaise khushiyon ka khazana!🏆",
  "Har din tumse baatein karke zindagi acchi lagti hai!🍀",
  "Tumhare saath time bitana toh sabse bada reward hai!🎁",
  "Kya kabhi tumhe samjha sakta hoon ki tum kitni special ho?💌",
  "Tumse dosti karne ka mann karta hai, par tumse alag bhi nahi ho sakta!💞",
  "Zindagi ke rang tumhare saath hi khilte hain!🌸",
  "Tum ho toh dil mein khushiyon ki bahar hai!🌼",
  "Har pal tumse milne ki aas lagata hoon!🎈",
  "Tumse milkar toh aisa lagta hai jaise sapne sach ho gaye!🌈",
  "Tumhara naam lete hi sab kuch accha lagta hai!📜",
  "Dil se keh raha hoon, tum ho toh sab kuch hai!🧡",
  "Tumhare saath waqt guzarte hi zindagi ki asli khushi milti hai!💎",
  "Tumhare bina sab kuch bekaar hai!😢",
  "Tumhare saath hona toh khud se milne jaisa hai!🌟",
  "Zindagi mein tumhe paa kar sab kuch paya!🏅",
  "Kya kabhi socha hai, tumse milkar duniya kitni sundar ho gayi hai?🖼️",
  "Tumhe dekhkar toh aisa lagta hai jaise sab kuch perfect hai!💖",
  "Mere sapno mein bhi tum hi ho!🌌",
  "Tumhe sochkar hi muskurahat aati hai!😁",
  "Tumhari dosti se zyada zaroorat kya hai?👐",
  "Tumhare bina toh har pal adhoora lagta hai!⏰",
  "Dil ki baatein samjhne wale ho toh samjho, tum bahut special ho!🎤",
  "Kya tumhe yaad hai, jab hum pehli baar mile the?💭",
  "Tum ho toh sab kuch beautiful hai!🌺",
  "Kya tum mujhe ek aur mauka doge, milne ka?👐",
  "Tumhare saath baatein karke hi din bita leta hoon!📅",
  "Tumhare bina yeh din bhi khaas nahi!🌅",
  "Tumhe paake aisa lagta hai jaise jeet gaya!🏆",
  "Kabhi kabhi sochta hoon, tumhe kis tarah se impress karoon!💝",
  "Tumhare bina dil ki khushi nahi!💔",
  "Tum meri muskurahat ka raaz ho!😄",
  "Kya tumhare bina khush rehna mumkin hai?🤷‍♂️",
  "Tum ho toh zindagi ka har pal rangin hai!🌈",
  "Aaj toh tumhare bina sab kuch suna suna lag raha hai!😞",
  "Tumhare saath guzaara har lamha khaas hai!💫",
  "Jab tum saath hote ho, sab kuch perfect lagta hai!🖌️",
  "Tumhari muskurahat se din chamak uthta hai!✨",
  "Tumse dosti karna meri sabse badi khushi hai!🎊",
  "Dil se keh raha hoon, tum ho toh sab kuch hai!💖",
  "Tumhare bina zindagi kuch khaas nahi!💔",
  "Kya tumhe pata hai, tum mere liye kitne important ho?📅",
  "Tumhare bina sab kuch suna suna hai!😞",
  "Tum ho toh zindagi ki asli rangin hai!🎨",
  "Kya tum mujhe ek baar phir se dekh sakte ho?👁️",
  "Tumhare saath waqt bitaana toh ek anmol khazana hai!🏆",
  "Dil se tumse keh raha hoon, tum sabse khaas ho!🌹",
  "Tumhe dekhkar har pal khush ho jata hoon!😁",
  "Kya kabhi socha hai, tumhare bina duniya kitni bekaar hoti?🌍",
  "Har din tumhe yaad karna mera shauk hai!💌",
  "Tumse mile bina toh aisa lagta hai, kuch khaas miss ho raha hai!🌟",
  "Kya tum mujhe apna dost banaoge?🤝",
  "Tum mere dil ke bahut kareeb ho!💓",
  "Tumhare saath baatein karke din bita leta hoon!📅",
  "Tumhe sochkar hi din bitaata hoon!🌞",
  "Tumhare saath har pal khaas hota hai!🎉",
  "Tumse pyaar karne ka mann karta hai!❤️",
  "Kya tumhare bina khud par control kar sakta hoon?🤷‍♂️",
 "Jab tum muskurate ho, jaise saari duniya roshan ho jati hai.🌟",
  "Tumhari aankhon mein chamak hai, jaise chaand ki roshni ne suraj ko chhup diya ho.🌙",
  "Tumhari khushi mere dil ka raag hai.🎶",
  "Zindagi ki har rangin tasveer tumhare bina adhoori hai.🎨",
  "Tum mere liye ek khwab ki tarah ho, hamesha khubsurat.💫",
  "Har pal tumhare saath bita kar mehsoos hota hai, jaise sapne sach ho gaye.🌈",
  "Tum ho toh har lamha suhaana lagta hai.🌸",
  "Tumhari muskurahat mere din ka pehla surya hai.🌅",
  "Tumhari yaad mere dil mein ek mehfil ki tarah hai.🕯️",
  "Jab bhi tum paas hoti ho, dil mein ek naya josh hai.❤️",
  "Tumhari baatein mere dil ki dhadkan ko hamesha badha deti hain.💖",
  "Tum ho toh zindagi mein rang hai, bina tumhare sab kuch suna hai.🌼",
  "Tumhare bina khud ko adhura mehsoos karta hoon.💔",
  "Kya tum samajhti ho, tumhari khushboo mere jeene ki wajah hai?🌷",
  "Tum mere sapnon ki raunak ho, har pal tumhare saath bitaana chahta hoon.✨",
  "Dil se keh raha hoon, tum mere liye sab kuch ho.🦋",
  "Tumhari muskurahat se mere din ki shuruaat hoti hai.☀️",
  "Tumhare saath bitaaye pal mere liye hamesha yaadgaar hain.📖",
  "Tum ho toh sab kuch sukoon hai, bina tumhare zindagi ek bhatak rahi hai.🌊",
  "Tumhare bina jeena adhoora hai, jaise khushboo bina phool.🌼",
  "Tumse baatein karke aisa lagta hai jaise khud se mil raha hoon.💬",
  "Tumhari aankhon ki gehraiyon mein kho jana chahta hoon.🌌",
  "Tum mere dil ka khazana ho, jise mein hamesha sambhal ke rakhna chahta hoon.💎",
  "Jab tum saath hoti ho, har pal khud ko khoj leta hoon.🔍",
  "Tumhare saath har subah ek nayi umeed jagati hai.🌅",
  "Tumse milne ka har lamha ek naya anubhav hai.🌺",
  "Tum meri zindagi ki ek sundar kahani ho.📚",
  "Tumhara saath mere sapnon ki tarah hai, hamesha khoobsurat.🌈",
  "Tumse mila toh aisa laga, jaise sab kuch accha ho gaya.🌟",
  "Tumhari khushboo se mehka hua har pal mere dil ko chhu jata hai.🌼",
  "Tum mere liye ek anmol ratan ho, jise mein hamesha sambhal ke rakhna chahta hoon.💍",
  "Tumhare saath har lamha ek nayi kahani ka shuruaat hoti hai.📖",
  "Zindagi ki har rangin tasveer tumhare saath hi khilti hai.🎨",
  "Tum meri khushiyon ka raaz ho, bina tumhare sab kuch suna hai.🌸",
  "Tumhari muskurahat se zindagi ki rangin khushboo hai.🌷",
  "Kabhi socha hai, tum meri zindagi ki ek khubsurat kahani ho?🖋️",
  "Tumhare bina har pal adhoora lagta hai, jaise ek geet bina sargam.🎵",
  "Tum mere liye ek anmol khazana ho, jise mein sambhal kar rakhna chahta hoon.💎",
  "Tumse milkar aisa lagta hai, jaise khushiyon ka khazana haath lag gaya.🌟",
  "Tum mere dil ki khushi ka raaz ho, hamesha khush rehna.💖",
  "Jab bhi tumhare saath hota hoon, dil khud ko khoj leta hai.💞",
  "Tum meri zindagi ki roshni ho, bina tumhare sab kuch andhera hai.🌙",
  "Tumse baatein karke aisa lagta hai jaise ek naya safar shuru hota hai.🚀",
  "Kya tum samajhti ho, tum mere sapno ki shaan ho?🌟",
  "Tum ho toh har pal khud par khush rehne ki wajah hai.😊",
  "Tumhari muskurahat se sab kuch khushnuma ho jata hai.🌞",
  "Zindagi ki har khushi tumhare saath hai, bina tumhare sab kuch suna hai.💔",
  "Tum mere liye ek sukoon ki tarah ho, hamesha dil ko chhu jati ho.🌼",
  "Tumse mila toh aisa laga, jaise khud par khushiyan bars rahi ho.🌧️",
  "Tum meri zindagi ki ek sundar kahani ka hissa ho.📖",
  "Tumhare bina toh khud ko adhura mehsoos karta hoon.💔",
  "Tum ho toh har lamha khud ko khoj leta hoon.💫",
  "Jab tum saath hoti ho, dil mein khushiyon ki baatein hoti hain.🗣️",
  "Tum mere sapnon ki roshni ho, bina tumhare sab kuch andhera hai.🌌",
  "Tumhari khushboo mere din ko mehka deti hai.🌷",
  "Kabhi socha hai, tum mere liye kitne khaas ho?💖",
  "Tum mere dil ka ek khubsurat hissa ho.❤️",
  "Tum ho toh har din naya raaz hai.✨",
  "Zindagi ke har rang mein tumhara saath hai.🎨",
  "Tumse milkar aisa lagta hai, jaise khushiyon ka khazana mila ho.🏆",
  "Tum meri muskurahat ka raaz ho, bina tumhare sab kuch suna hai.💔",
  "Tumhare saath guzaara har lamha khaas hai.💓",
  "Kya kabhi tumhare bina khud par control kar sakta hoon?🤷‍♂️",
  "Tum mere sapnon ki roshni ho, hamesha chamak rahi ho.🌟",
  "Tumse dosti karne ka mann karta hai, par tumse alag bhi nahi ho sakta!💞",
  "Tumhare saath bitaaye pal mere liye ek naya anubhav hain.💖",
  "Jab tum paas hoti ho, dil mein khushiyon ki baatein hoti hain.💬",
  "Tum meri zindagi ki ek anmol kahani ho.📚",
  "Tumse baatein karke dil ko sukoon milta hai.🌊",
  "Tum ho toh sab kuch khubsurat hai.💝",
  "Zindagi ki har rangin tasveer tumhare bina adhoori hai.🌸",
  "Tumhari aankhon ki gehraiyon mein kho jana chahta hoon.🌌",
  "Tum mere liye ek khwab ki tarah ho, hamesha khubsurat.💫",
  "Tumhare bina zindagi kuch khaas nahi!💔",
      "Tum mere sapnon ki raunak ho, har pal tumhare saath bitaana chahta hoon.✨",
    ];

    const randomResponse = responses[Math.floor(Math.random() * responses.length)];

    const mention = [{ id: senderID, tag: name }];

    if (event.body.toLowerCase() === "bot") {
      const msg = {
        body: `🥀 ${name} 🥀\n\n『 ${randomResponse} 』`,
        mentions: mention 
      };
      return api.sendMessage(msg, threadID, messageID);
    }
  }
};
